exp: TextClassification

mode: 
    - train

models:
    hf_text_classification_model:
      - JIWON/bert-base-finetuned-nli
      
trainfpath: final/data/sym_sample_data.tsv
validfpath: final/data/sym_sample_data.tsv 

numLabels: 3
modelfpath: final/models/sym_nli