exp: TextClassification

mode: 
    - evaluate
    - analyze

models:
    hf_text_classification_model:
        - ./sym_nli

predfpath: final/predictions/sym_on_mono.tsv
datafpath: final/data/MoNLI_sample.tsv
resultsfpath: final/results/sym_on_mono.tsv

textlabel: text
pairlabel: pair
device: cuda
conditions: condition

save: by_cond, by_target

id2label:
    2: contradiction
    1: entailment
    0: neutral